version: "3.8"

services:
  axe_delivery_db:
    image: postgres:alpine
    container_name: axd_db
    restart: always
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  axe_delivery_backend:
    build: ./backend
    container_name: axd_backend
    restart: always
    ports:
      - 3030:3030
      - 9339:9339
    volumes:
      - ./backend:/usr/axd/backend
    links:
      - axe_delivery_db
    depends_on:
      - axe_delivery_db

  # soilaxe_delivery_frontend:
  #   build: ./frontend
  #   container_name: axd_backend
  #   restart: always
  #   ports:
  #     - 3003:3000
  #   volumes:
  #     - ./frontend:/usr/axd/frontend
  #   links:
  #     - axe_delivery_backend
  #   depends_on:
  #     - axe_delivery_backend
